before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - # Comments
    id: "dnscheck"
    main: ./cmd/dnscheck/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      # - darwin

archives:
  - format: tar.gz
    files:
    - LICENSE
    - README.md
    - src: configs/dnscheck.yaml
      dst: dnscheck.yaml
    format_overrides:
    - goos: windows
      format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  # note that this is an array of nfpm configs
  - #
    # ID of the nfpm config, must be unique.
    #
    # Default: 'default'
    id: default

    # Name of the package.
    # Default: ProjectName
    # Templates: allowed. (since v1.18)
    package_name: dnscheck

    # You can change the file name of the package.
    #
    # Default: '{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    # Templates: allowed.
    file_name_template: "{{ .ConventionalFileName }}"

    # Build IDs for the builds you want to create NFPM packages for.
    # Defaults empty, which means no filtering.
    # builds:
    #   - foo
    #   - bar

    # Your app's vendor.
    vendor: micophi

    # Your app's homepage.
    homepage: https://github.com/Micophi/dnscheck

    # Your app's maintainer (probably you).
    maintainer: Micophi <micophi@protonmail.com>

    # Your app's description.
    description: |-
      Dnscheck installer package.
      Software to test the blocking abilities of DNS servers against a list of malicious domain names.

    # Your app's license.
    license: MIT

    # Formats to be generated.
    formats:
      - deb

    umask: 0o002

    # Packages your package depends on. (overridable)
    dependencies:
      - bash
      - curl
      - moreutils

    bindir: /usr/bin
    # version_metadata: git

    # Version Release.
    # release: 1

    # Section.
    section: default

    # Priority.
    priority: extra

    contents:
      - src: configs/dnscheck.yaml
        dst: /etc/{{ .ProjectName }}/dnscheck.yaml
      - src: scripts/*.sh
        dst: /usr/bin

    # Custom configuration applied only to the Deb packager.
    deb:
      # Lintian overrides
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

      # The package is signed if a key_file is set
      signature:
        # PGP secret key file path (can also be ASCII-armored).
        # The passphrase is taken from the environment variable
        # `$NFPM_ID_DEB_PASSPHRASE` with a fallback to `$NFPM_ID_PASSPHRASE`,
        # where ID is the id of the current nfpm config.
        # The id will be transformed to uppercase.
        # E.g. If your nfpm id is 'default' then the deb-specific passphrase
        # should be set as `$NFPM_DEFAULT_DEB_PASSPHRASE`
        #
        # Templates: allowed.
        # key_file: "{{ .Env.GPG_KEY_PATH }}"

        # The type describes the signers role, possible values are "origin",
        # "maint" and "archive".
        #
        # Default: 'origin'
        type: origin
