---
rateLimit: 100
dnsservers:
  - name: Quad9
    description: Malware Blocking, DNSSEC Validation
    ip: https://dns.quad9.net/dns-query
    # rateLimit: 10
  - name: Quad9 Secured
    description: "Secured w/ECS: Malware blocking, DNSSEC Validation, ECS enabled"
    ip: https://dns11.quad9.net/dns-query
  - name: Quad9 Unsecured
    description: "Unsecured: No Malware blocking, no DNSSEC validation (for experts only!)"
    ip: https://dns10.quad9.net/dns-query
  - name: Cloudflare
    description: Cloudflare DNS(https://1.1.1.1/)
    ip: https://cloudflare-dns.com/dns-query
  - name: Google
    description: Google DNS (https://developers.google.com/speed/public-dns)
    ip: https://dns.google/dns-query
  - name: OpenDNS
    description: OpenDNS Family Shield
    ip: https://doh.familyshield.opendns.com/dns-query
  - name: CIRA Private
    description: DNS resolution only
    ip: https://private.canadianshield.cira.ca/dns-query
  - name: CIRA Protected
    description: Malware and phishing protection
    ip: https://protected.canadianshield.cira.ca/dns-query
  - name: CIRA Family
    description: Protected + blocking pornographic content
    ip: https://family.canadianshield.cira.ca/dns-query
  - name: Adguard
    description: Block ads and trackers
    ip: https://dns.adguard-dns.com/dns-query	
  - name: Adguard Non-Filtering
    description: Does not block ads, trackers, or any other DNS requests
    ip: https://unfiltered.adguard-dns.com/dns-query
  - name: Adguard Family protection
    description: Block ads, trackers, adult content, and enable Safe Search and Safe Mode, where possible
    ip: https://family.adguard-dns.com/dns-query
    