# .github/workflows/release.yml
name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.deb
            dist/*.tar.gz
            dist/*.zip
            LICENSE
      - name: push package to packagecloud.io
        uses: computology/packagecloud-github-action@v0.9
        with:
          PACKAGE-NAME: dist/*.deb
          PACKAGECLOUD-USERNAME: micophi
          PACKAGECLOUD-REPONAME: dnscheck
          PACKAGECLOUD-DISTRO: debian
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}
